version: "3.9"
services:
  qpdf:
    env_file:
      - .env
    image: ghcr.io/ptorrezao/qpdftool_payslip/qpdftool:latest
    build: .
    volumes:
      - ./docs:/work/docs
      - ./scripts:/work/scripts
      - ./output:/work/output